language: ruby
rvm:
  - 2.6.3
script: "./script/cibuild.sh"
branches:
  only:
  - content
env:
  global:
    secure: "haaJCYoQ2OuCu9B9pmHBOQVvzTvzSfLzQHOzwYan/VAvJTb+luVquk438OCgWKa8VloWk3ciArA6chppGsZFIwo/4R03fPK7WmXvukYMrYBBF0pRoBfaSgNTIsOdBNZhmGsnqKL5RGZUuoMdpw81bnv28yqbj/a5sPFdZDXGDm57fOLbRbDT6ZYRDzY7wC3+4JlA3+EaNplcLxUvhxl8vJjN0QMjIY21q3SsNJuhhFztVdyZtxhxRiful3RA5bjeVx5g6gHY7L0rzPaLFZ6ymtV6tUofTbvA+h9AdIHZRIy4/IL/CpLFUUloK+ihQYx3dQM73joifxqmbNMdveQof/6+C2NePrFL8YaOQrk4uH+pKSxTpC7u2lwRES3FKEEunB8sQDSmO7uA14GxsTAhAvXj6DfcQ46IJwQ381eXx7SWNdLGXcuK+IDRV9b7JZgja6fmKzR96VDdTgl966EYmjD9D56brtvFpY6iaxF1nho3RWkYbnyuSRCTsfazPhw2PwNDQn1/0+2mHsp0g1+NufKeQwSPZd8dbuEVvYH1d3NHCNg1kvgHGWu8QH1rHci0fznjyFk3tbz+caNPjKYZqNkMRQheLNY+LzJqDDZTXbwb4cCipJP5PIu5ZW690DYE7d2Nd0FzIc7FocxGde9ZAuRRSYaVIu2nAlV51b76IAI="
