name: Substeps - BDD Framework
description: Substeps Documentation
markdown: kramdown
highlighter: rouge
permalink: pretty
encoding: utf-8
#code_examples_folder: _code_examples
#host: 0.0.0.0
#excerpt_separator: "\n\n\n\n"
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude: [vendor]